# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb5b7397e1b9f528eb5ecd9b5c32c55e6fa3f91a98b692e51154e7957d63f2c0f1441db67cf8faa408450eebe0d02072e282f5ef2e4c5d3053049918badec6aa

test:
  secret_key_base: d21beb08a3c164f1fbdb95ceb50cb1f756f22ee62d9e7cd2c86adda39d71c1d29fbe5d3e1cdeac248f9d65af9b7d1ca7eded3c4b643b2487d4ece9fd0903f93b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
